name              'unzip_fx'
maintainer        'fxinnovation'
maintainer_email  'cloudsquad@fxinnovation.com'
license           'MIT'
description       'Provides a resource to download and unzip a file'
version           '0.1.0'
source_url        'https://bitbucket.org/fxadmin/public-common-cookbook-unzip_fx'
issues_url        'https://bitbucket.org/fxadmin/public-common-cookbook-unzip_fx/issues'
chef_version      '>= 12.5' if respond_to?(:chef_version)
supports          'windows'
supports          'redhat'
supports          'centos'
supports          'debian'
supports          'ubuntu'
